In [1]:
import math

In [2]:
import numpy as np

In [9]:
revenue=np.array([[100,200,220],[24,36,40],[12,18,20]])
revenue

array([[100, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [10]:
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [12]:
profit= revenue - expenses
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [14]:
price=np.array([1000,400,1200])
price

array([1000,  400, 1200])

In [17]:
units=np.array([[30,40,50],[5,10,15],[2,5,7]])
units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [18]:
price*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

why because it is numpy boracd casting it has taken value fromanother colums 

In [20]:
np.dot(price,units)

array([34400, 50000, 64400])

In [22]:
rev=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
rev

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [23]:
price=75

In [24]:
rev*price

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])